### ISSUE TITLE
problem with 1.9.1 image

### ISSUE THREAD

**Issue by thmo** [hedgedoc/container#270]
Here, updating to [1.9.1](quay.io/hedgedoc/hedgedoc:1.9.1) yields:
```
app_1       | 2021-12-02T22:47:22.674Z info: 	127.0.0.1 - - [02/Dec/2021:22:47:22 +0000] "GET /status HTTP/1.1" 500 148 "-" "node-fetch/1.0 (+https://github.com/bitinn/node-fetch)"
app_1       | TypeError: Cannot read properties of undefined (reading 'passport')
app_1       |     at SessionStrategy.authenticate (/hedgedoc/node_modules/passport/lib/strategies/session.js:51:18)
app_1       |     at attempt (/hedgedoc/node_modules/passport/lib/middleware/authenticate.js:360:16)
app_1       |     at authenticate (/hedgedoc/node_modules/passport/lib/middleware/authenticate.js:361:7)
app_1       |     at Layer.handle [as handle_request] (/hedgedoc/node_modules/express/lib/router/layer.js:95:5)
app_1       |     at trim_prefix (/hedgedoc/node_modules/express/lib/router/index.js:317:13)
app_1       |     at /hedgedoc/node_modules/express/lib/router/index.js:284:7
app_1       |     at Function.process_params (/hedgedoc/node_modules/express/lib/router/index.js:335:12)
app_1       |     at next (/hedgedoc/node_modules/express/lib/router/index.js:275:10)
app_1       |     at initialize (/hedgedoc/node_modules/passport/lib/middleware/initialize.js:66:5)
app_1       |     at Layer.handle [as handle_request] (/hedgedoc/node_modules/express/lib/router/layer.js:95:5)
app_1       |     at trim_prefix (/hedgedoc/node_modules/express/lib/router/index.js:317:13)
app_1       |     at /hedgedoc/node_modules/express/lib/router/index.js:284:7
app_1       |     at Function.process_params (/hedgedoc/node_modules/express/lib/router/index.js:335:12)
app_1       |     at next (/hedgedoc/node_modules/express/lib/router/index.js:275:10)
app_1       |     at /hedgedoc/node_modules/connect-flash/lib/flash.js:21:5
app_1       |     at Layer.handle [as handle_request] (/hedgedoc/node_modules/express/lib/router/layer.js:95:5)
app_1       |     at trim_prefix (/hedgedoc/node_modules/express/lib/router/index.js:317:13)
app_1       |     at /hedgedoc/node_modules/express/lib/router/index.js:284:7
app_1       |     at Function.process_params (/hedgedoc/node_modules/express/lib/router/index.js:335:12)
app_1       |     at next (/hedgedoc/node_modules/express/lib/router/index.js:275:10)
app_1       |     at module.exports (/hedgedoc/lib/web/middleware/tooBusy.js:14:5)
app_1       |     at Layer.handle [as handle_request] (/hedgedoc/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by davidmehren** [comment]
We just released HedgeDoc 1.9.2 to fix this issue. Container images should be available shortly.
Thanks for reporting!
